{{- if or .Values.postgres.enabled .Values.mysql.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "openfga.fullname" . }}-migrate
  labels:
    {{- include "openfga.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
spec:
  template:
    spec:
      containers:
        - name: migrate-database
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["migrate"]
          env:
            {{- if .Values.datastore.engine }}
            - name: OPENFGA_DATASTORE_ENGINE
              value: "{{ .Values.datastore.engine }}"
            {{- end }}

            {{- if .Values.datastore.uri }}
            - name: OPENFGA_DATASTORE_URI
              value: "{{ .Values.datastore.uri }}"
            {{- else if .Values.datastore.uriSecret }}
            - name: OPENFGA_DATASTORE_URI
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.datastore.uriSecret }}"
                  key: "uri"
            {{- end }}
      restartPolicy: Never
  backoffLimit: 1
{{- end }}